# Generated by Django 4.2.27 on 2026-01-22 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('placa', models.CharField(help_text='Formato: ABC-123', max_length=10, verbose_name='Placa')),
                ('tipo_vehiculo', models.CharField(choices=[('Turbo', 'Turbo'), ('Sencillo', 'Sencillo'), ('Eléctrico', 'Eléctrico')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('numero_entregas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Entregas')),
                ('facturacion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Facturación')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
